### ISSUE TITLE
tty login

### ISSUE THREAD

**Issue by madprops** [c3ks/node-webterminal#4]
Hi thanks for this great project. I got the terminal working but it is logging automatically as the user that is running the application. So I was wondering is there a way to force the tty to prompt for a login?

**Comment by Gottox** [comment]
Thank you :)

Search app.js for the line starting with "new PtyController(socket, "

change the second argument to an executable. For a login prompt, defining /bin/login or /usr/bin/login (depends on the system) as the executable should do the job.
